#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

head -1 copilot-instructions.md | grep -q '^<!-- GENERATED by ~/.agents/bin/agents-sync' &&
  fail 'copilot-instructions.md still has generated banner'

if rg -q '\.agents/(core|rules|hooks)(/|`|$)' copilot-instructions.md; then
  fail 'instructions still reference .agents control plane'
fi

for file in hooks/guard-git-push.json hooks/guard-git-push.sh; do
  [ -f "$file" ] || fail "local hook missing: $file"
done
for rule in cookbook cpp dotnet frontend-spa infra testing typescript winforms; do
  [ -f "rules/$rule.md" ] || fail "local stack rule missing: rules/$rule.md"
done

bytes=$(wc -c < copilot-instructions.md | tr -d ' ')
[ "$bytes" -le 4000 ] || fail "copilot-instructions.md exceeds thin budget: ${bytes}B"
[ "$bytes" -lt 3600 ] || fail "copilot-instructions.md must stay below 90% of its 4000B budget: ${bytes}B"

for rule in T0-1 T0-2 T0-3 T0-4 T0-5 T0-6 T0-7 T0-8 T0-9; do
  rg -q "\\[$rule\\]" copilot-instructions.md || fail "Tier 0 rule missing: $rule"
done

rg -q '~/.agents/skills/dev-workflow/SKILL\.md' copilot-instructions.md ||
  fail 'shared dev-workflow route missing'

# 逐行 pin，與 ~/.claude/tests/repo-integrity.sh 及 ~/.codex/tests/global-config-ownership.sh
# 的同名斷言對齊——canonical 行散在 6 個檔（三份指令檔 + 三支測試），且 Claude／Codex 帶
# 前導 `- `、Copilot 是段落無前導，措辭若合法變更必須六處同步且不可無腦複製。
# delegation-policy-parity.sh 除了 `grep -Fq '[INT-4]'` 這條 token 檢查外只比對語意
# （autonomy／no-ask／無固定上限），所以保留 [INT-4] 而只改措辭一律會過——2026-08-03
# 實測本行曾漂成「Delegation：[INT-4] 由 AI 自主判定，無須另問。」，掉了
# `依 shared dev-workflow` 這個指向正本的錨點，而三支 gate 全綠。三家只有 Copilot 沒逐行
# pin，所以只有這裡漂得掉。
# shellcheck disable=SC2016  # 單引號是刻意的：要比對的字面就含反引號，展開反而錯
grep -Fqx -- 'Delegation：依 shared `dev-workflow` [INT-4] 由 AI 自主判定，無須另問。' copilot-instructions.md ||
  fail 'Copilot delegation adapter must stay thin and point to shared INT-4'

jq -e '
  .mcpServers.context7.tools == ["resolve-library-id", "query-docs"] and
  .mcpServers.context7.args[-1] == "@upstash/context7-mcp@3.2.5" and
  (.mcpServers["microsoft-learn"] == null)
' mcp-config.json >/dev/null ||
  fail 'Context7 must be pinned/exact-tool scoped and microsoft-learn must stay plugin-owned'

zshrc_path="${HOME}/.zshrc"
if [ "${CI:-}" = true ]; then
  printf 'SKIP: live ~/.zshrc Context7 approval wrapper is host-only\n'
elif [ ! -f "$zshrc_path" ]; then
  fail 'live ~/.zshrc missing; cannot verify Context7 approval wrapper'
elif zsh -n "$zshrc_path" &&
     grep -Fq "local context7_tools='context7(resolve-library-id),context7(query-docs)'" "$zshrc_path" &&
     grep -Fq 'command copilot --allow-tool="$context7_tools" "$@"' "$zshrc_path" &&
     grep -Fq 'command copilot --autopilot --allow-tool="$context7_tools" "$@"' "$zshrc_path" &&
     grep -Fq 'copilot --autopilot "$@"' "$zshrc_path"; then
  :
else
  fail 'Copilot launcher must auto-approve only the two Context7 read-only tools'
fi

if rg -q 'Matt workflow integration|Routing 對照表|Anti-duplication|^### S[456]|reasoning_effort|plugin-contributed reviewer' copilot-instructions.md; then
  fail 'Copilot instructions duplicate shared workflow policy'
fi

# settings.json is app-managed and intentionally ignored; validate it only on the live host.
if [ -f settings.json ]; then
  jq -e '.enabledPlugins["code-review@claude-plugins-official"] == null' settings.json >/dev/null ||
    fail 'stale code-review plugin setting remains'
  jq -e '.enabledPlugins["pr-review-toolkit@claude-plugins-official"] == false' settings.json >/dev/null ||
    fail 'overlapping pr-review-toolkit plugin remains enabled'
  jq -e '
    [paths(scalars) as $path
      | {path: ($path | map(tostring) | join(".")), value: getpath($path)}
      | select((.path | test("reason.*effort"; "i")) and .value != null)]
    | length == 0
  ' settings.json >/dev/null || fail 'settings contains a fixed reasoning effort'
  settings_status=PASS
else
  settings_status=SKIPPED
  printf 'SKIP: app-managed settings unavailable\n'
fi

# CONVENTIONS 規則 11 的 host 一側。必須用 find 不得用 ls + glob：後者在 zsh 下任一目錄
# 無匹配即 nomatch 中止並回 0＝假合規（2026-07-30 實測同指令 zsh 回 0、bash 回 4）。
# dotfile 排除＝規則 11 的「app 自管 runtime state 備份」例外。
# 本 repo 無 hooks/drift-check.sh（只有 guard-git-push.{json,sh}），故不含 parity guard 斷言。
manual_bak="$(find . -maxdepth 1 -name '*.bak*' -not -name '.*' 2>/dev/null | tr '\n' ' ')"
[ -z "$manual_bak" ] || fail "manual .bak present (CONVENTIONS rule 11): $manual_bak"

printf 'PASS: Copilot global config ownership (settings: %s)\n' "$settings_status"
