#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

head -1 copilot-instructions.md | grep -q '^<!-- GENERATED by ~/.agents/bin/agents-sync' &&
  fail 'copilot-instructions.md still has generated banner'

if rg -q '\.agents/(core|rules|hooks)(/|`|$)' copilot-instructions.md; then
  fail 'instructions still reference .agents control plane'
fi

for file in hooks/guard-git-push.json hooks/guard-git-push.sh; do
  [ -f "$file" ] || fail "local hook missing: $file"
done
for rule in cookbook cpp dotnet frontend-spa infra testing typescript winforms; do
  [ -f "rules/$rule.md" ] || fail "local stack rule missing: rules/$rule.md"
done

bytes=$(wc -c < copilot-instructions.md | tr -d ' ')
[ "$bytes" -le 7000 ] || fail "copilot-instructions.md exceeds thin budget: ${bytes}B"

for marker in dev-workflow S4 S5 S6 grilling domain-modeling implement tdd diagnosing-bugs code-review codebase-design; do
  rg -q "$marker" copilot-instructions.md || fail "thin route missing: $marker"
done

rg -q '~/.agents/skills/dev-workflow/SKILL\.md' copilot-instructions.md ||
  fail 'shared dev-workflow route missing'

if rg -q '^# tier[12]|superpowers:|mp-(diagnose|grill-with-docs|improve-codebase-architecture|tdd)' copilot-instructions.md; then
  fail 'Copilot instructions still contain legacy/non-thin workflow'
fi

printf 'PASS: Copilot global config ownership\n'
