#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

head -1 copilot-instructions.md | grep -q '^<!-- GENERATED by ~/.agents/bin/agents-sync' &&
  fail 'copilot-instructions.md still has generated banner'

if rg -q '\.agents/(core|rules|hooks)(/|`|$)' copilot-instructions.md; then
  fail 'instructions still reference .agents control plane'
fi

for file in hooks/guard-git-push.json hooks/guard-git-push.sh; do
  [ -f "$file" ] || fail "local hook missing: $file"
done
for rule in cookbook cpp dotnet frontend-spa infra testing typescript winforms; do
  [ -f "rules/$rule.md" ] || fail "local stack rule missing: rules/$rule.md"
done

printf 'PASS: Copilot global config ownership\n'
